# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/remote.php/webdav/"
username = "cristianabastos.98@gmail.com"
password = "HCFII-VTGVG-KXAMY-JBRUN"